gtnh.settings.blowdryerTag = 0.2.2

modName = GTNH AI Bot
modId = gtnh_ai_bot
modGroup = dev.nottambok.gtnhaibot
useModGroupForPublishing = true
autoUpdateBuildScript = false

minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/
developmentEnvironmentUserName = Developer

enableModernJavaSyntax = false
enableGenericInjection = true

generateGradleTokenClass = dev.nottambok.gtnhaibot.Tags
gradleTokenVersion = VERSION
apiPackage =
accessTransformersFile =

usesMixins = false
separateMixinSourceSet =
usesMixinDebug = false
mixinPlugin =
mixinsPackage =
coreModClass =
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false

usesShadowedDependencies = false
minimizeShadowedDependencies = true
relocateShadowedDependencies = true

includeWellKnownRepositories = true
excludeWellKnownRepositories =

usesMavenPublishing = false
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =
gtnh.modules.gitVersion = false

org.gradle.configuration-cache = true
org.gradle.parallel = true
